language: java
jdk: openjdk7

env:
  global:
    # Terminal does not support colors (Gradle display issue)
    - TERM=dumb
    
    # Syncany FTP credentials (SYNCANY_FTP_* environment variables)
    - secure: "OWv7tJZiDQYxZpxw25Qs4B086veBPzjGvrVApfd8tAAOI7xG8Ifp9+TFsRO27xw99ZDFDLzjSZyffR45sgGCTuRapdSWNwIEmma4dAn299bFl1ayU5IXQYtIRsaXjyAm8QPmLbdl5YHFE77ArzFIsaysb7ZXB3cKnYfJGkiNLFs="
    - secure: "I0+Aw5CgV5wGfsW8hO/HB9FgCUQI/UDg1ppUV7ATq6UpaxmftSpycxR5TOx3D1ISewoD079BqLxSB1i4grns5vKccGxgjeGt4vFr3X1c1NHth0jOPVMJDEVcKZ4odxM8BbSa4MOk+ZpqsgjfDqGZzxt8eRBai1chlKx8WEKao+4="
    - secure: "JPLqhdDfP3y12dlCtyNfNg32vEQzJAKAp9CFrvz1uogZr61bp0NEi3cDS2TGSqWep7X/uPgJ84LFI22Fy5zH/1pJxY9Y9NpmVnRtFy9Cp3Qb0A9fUZ2ePO2TtyHBwLHCDO9FolrhPpqX6WuCSW26igIEzyAwaslFAJUhF09qadw="

    # Syncany GPG signing stuff (SYNCANY_GPG_* environment variables)
    - secure: "JV+cvV8BgYC9i1EUthycCDfX5rVqlptSaewW03JniEfA5fJnaiQylnDRd72Cev+vcUpgphPXMAXZDP0++hxeOaMsntJBQGgUMv3+DHJ2+JFn9rO5XjrqsIpbBMqwF7Ph89ImFzx4blk3uch3cF7O4DWU00E77AN8xoh7VkkMuDM="
    - secure: "lhltKRuNNed9y7wNTbh5Qr1Ubs51Fp6nbNFJkYqjYyi4WOIR8/SfeAcrON6pdVVHRwQa/1/HSwXhsB7EXSdgrTnYdlxn+6t8GdHyYiQazrXmqrIJGmFEESyo0iMoXuF4jnw4kWPayH7tDC/+J6kPaLSkyND0s5/loBiHtlGXWwc="
    
branches:
  only:
    - master
    - develop
    
notifications:
  email: false
  irc: "chat.freenode.net#syncany"
  
before_install:
  # Update APT (necessary!)
  - sudo apt-get update

  # Debian and PPA 
  - sudo apt-get install -y -q gnupg dh-make devscripts dput devscripts debhelper 
  - gpg --version
  - dput -v
  - debuild --version
  - perl -v
  
  # LFTP (to upload the distributables and JavaDoc)
  - sudo apt-get install -y -q lftp 
  - lftp -v 

  # Graphviz (for JavaDoc images; see Gradle tasks)
  - sudo apt-get install -y -q graphviz 
  
  # Inno Setup (for Windows executable/installer)
  - sudo add-apt-repository --yes ppa:arx/release
  - sudo apt-get update -d
  - sudo apt-get install -y -q innoextract wine python-software-properties
  - wine --version 
  - innoextract --version 
  - ./gradle/innosetup/innoinstall.sh
  - sudo cp gradle/innosetup/iscc /usr/local/bin/iscc
  - iscc /? 2> /dev/null | grep "Inno Setup Preprocessor"

  # Line of code tool (cloc)
  - sudo apt-get install -y -q cloc
  - cloc --version

install:
  # Disable default travis behavior 'gradle assemble'
  - ./gradlew -v

script: 
  # Run JUnit tests and generate reports
  - ./gradlew testGlobal coberturaReport performCoverageCheck javadocAll

after_success:
  # Line of code stats
  - cloc --quiet --xml --out=build/reports/cloc.xml $(find -type d -name main | grep src/main)
 
  # Upload to PPA
  - ./gradlew debianPreparePrecise ppa
  - ./gradlew debianPrepareSaucy ppa
  - ./gradlew debianPrepareTrusty ppa
  
  # Create distributables and JavaDoc
  - ./gradlew installApp distTar distZip debianPrepareUnstable debian exe 
    
  # Upload distributables and JavaDoc
  - ./gradle/lftp/lftpupload.sh

